### ISSUE TITLE
T13.1 Look for related work to our visualizations

### ISSUE THREAD

**Issue by JortvD** [GR47BD/research-paper#1]
For each group working on the visualizations.

**Comment by B0bby31** [comment]
Here are some archives to look for papers: (Of course, dont restrict urselfs to these)
https://dblp.org/ -> mainly computer science
https://scholar.google.com/
https://www.base-search.net/
https://citeseerx.ist.psu.edu/ -> mainly computer science, math
https://core.ac.uk/
https://en.wikipedia.org/wiki/List_of_academic_databases_and_search_engines -> to find more search engines

The ones I listed seemed to have had interesting results when I searched some keywords...
